Fix checking global.screen (repairs 3.28)
Otherwise, `("screen" in global)` is `false` and the extension breaks with

```
Error: No signal 'in-fullscreen-changed' on object 'MetaDisplay'
```

Signed-off-by: Vadim Markovtsev <vadim@sourced.tech>